version: 0.2

env:
  variables:
    SOLUTION: .\MicroServices.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.6.1

phases:
  build:
    commands:
      - '& "C:\ProgramData\chocolatey\bin\NuGet.exe" restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      #- '& "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\MSBuild.exe" Services\CoreService\CoreService.csproj  /t:Rebuild /p:Configuration=Release /p:Platform=x64'
      - '& "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\MSBuild.exe" Services\NetService\NetService.csproj  /t:Rebuild /p:Configuration=Release /p:Platform=AnyCPU'
      - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\MSBuild.exe" Services\CoreService\CoreService.csproj  /t:Rebuild /p:Configuration=Release /p:Platform=x64'
      - '& MSBuild Services\CoreService\CoreService.csproj  /t:Rebuild /p:Configuration=Release /p:Platform=x64'
      - ' MSBuild Services\CoreService\CoreService.csproj  /t:Rebuild /p:Configuration=Release /p:Platform=x64'
artifacts:
  files:
    - .\Services\NetService\bin\*
    - .\BIN\CoreService\netcoreapp2.0\*