version: 0.2

env:
  variables:
    SOLUTION: .\MicroServices.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.6.1

phases:
  build:
    commands:
      #- '& "C:\ProgramData\chocolatey\bin\NuGet.exe" restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - dotnet restore Services\CoreService\CoreService.csproj'
      - dotnet build Services\CoreService\CoreService.csproj'
      - '& "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\MSBuild.exe" Services\NetService\NetService.csproj  /t:Rebuild /p:Configuration=Release /p:Platform=AnyCPU -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1"'
artifacts:
  files:
    - .\Services\NetService\bin\*
    - .\BIN\CoreService\netcoreapp2.0\*