version: '3.4'

services:
  microservices:
    image: ${DOCKER_REGISTRY}microservices
    build:
      context: .
      dockerfile: MicroServices\Dockerfile

  coreservice:
    image: ${DOCKER_REGISTRY}coreservice
    build:
      context: .
      dockerfile: CoreService\Dockerfile


  netservice:
    image: ${DOCKER_REGISTRY}netservice
    build:
      context: .\Services\NetService
      dockerfile: Dockerfile

